config/routes.rb
Rails.application.routes.draw do

  resources :reviews do
    resources :posts
  end

  resources :profiles

  devise_for :users
  root :to => 'home#index'
  get 'home/index'

  resources :tours
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

end

app/models/tour.rb
class Tour < ActiveRecord::Base
end

app/controllers/tours_controller.rb
require 'tour_decorator'
require 'my_logger'

class ToursController < ApplicationController
  before_filter :authenticate_user! 
  before_filter :ensure_admin, :only => [:edit, :destroy]
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  
  def ensure_admin
    unless current_user && current_user.admin?
    render :text => "Access Error Message", :status => :unatuhorized
    end
  end
  
  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)
    
    @tour.firstname = params[:tour][:firstname]
    @tour.lastname = params[:tour][:lastname]
    @tour.language = params[:tour][:language]
    
    #create an instance/object of a BasicTour
    myTour = BasicTour.new(0, @tour.language)
    # add the extra features
    if params[:tour][:windows].to_s.length > 0 then
      myTour = ElectricWindowsDecorator.new(myTour)
    end

    if params[:tour][:mirror].to_s.length > 0 then
      myTour = MirrorDecorator.new(myTour)
    end
    
    if params[:tour][:psensor].to_s.length > 0 then
      myTour = ParkingSensorDecorator.new(myTour)
    end
    
    #popuate the cost and description details
    @tour.cost = myTour.cost
    @tour.description = myTour.details
    
    #retrieve the instance/object of the MyLogger class
    logger = MyLogger.instance
    logger.logInformation("a new car requested:" + @tour.description)
    
    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    
    #update the instance variables with the information
    #user provided in the form
    #retrieve each value from the params hash
    @tour.firstname = params[:tour][:firstname]
    @tour.lastname = params[:tour][:lastname]
    @tour.language = params[:tour][:language]
    
    #create and instance/object of a BasicTour
    myTour = BasicTour.new(10, @tour.language)
    
    #add the extra features
    if params[:tour][:windows].to_s.length > 0 then
      myTour = ElectricWindowsDecorator.new(myTour)
    end
    
    if params[:tour][:mirror].to_s.length > 0 then
      myTour = MirrorDecorator.new(myTour)
    end
    
    if params[:tour][:psensor].to_s.length > 0 then
      myTour = ParkingSensorDecorator.new(myTour)
    end
    
    #update the cost and the description details.
    @tour.cost = myTour.cost
    @tour.description = myTour.details
    
    #build a hash with the updated information of the car
    updated_information = {
      "firstname" => @tour.firstname,
      "lastname" => @tour.lastname,
      "language" => @tour.language,
      "cost" => @tour.cost
    }
    
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:firstname, :lastname, :language, :cost, :description)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <h2>Pick the Tours you would like to go on</h2>
  
  <div class="field">Haunted House Tour: 
  <%=check_box_tag 'tour[windows]','windows' %>
  </div>
  
    <div class="field">3 Hour Walk Tour: 
  <%=check_box_tag 'tour[mirror]','mirror' %>
  </div>
  
    <div class="field">5 Hour Walk Tour: 
  <%=check_box_tag 'tour[psensor]','psensor' %>
  </div>
 
  <div class="field"> 3 Hour Bus Tour: 
  <%=check_box_tag 'tour[tlights]','tlights' %>
  </div>
 
    <div class="field">Pub Crawl: 
  <%=check_box_tag 'tour[blights]','blights' %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="/assets/stylesheets/application.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="utf-8" />
    <title>Tour Guide Application</title>
    <style>


</style>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Tour Guide Application</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="users/sign_in">SignIn/Sign up</a></li>
        <li><a href="reviews">Reviews</a></li>
        <li><a href="tours">List of Booked Tours</a></li>
        <li><a href="tours/new">Book a Tour</a></li>
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</head>

<body style="background-color:darkgrey;"><center>
<p id="notice"><%= notice %></p>

<h1>Listing Tours</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Language</th>
      <th>Cost</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.firstname %></td>
        <td><%= tour.lastname %></td>
        <td><%= tour.language %></td>
        <td><%= tour.cost %></td>
        <td><%= tour.description %></td>
        <td><%= link_to 'Show', tour %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Tour', new_tour_path %>
<% end %>

</body>
</html>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @tour.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @tour.lastname %>
</p>

<p>
  <strong>Language:</strong>
  <%= @tour.language %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @tour.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>