config/routes.rb
Rails.application.routes.draw do

  resources :reviews do
    resources :posts
  end

  resources :profiles

  devise_for :users
  root :to => 'home#index'
  get 'home/index'

  resources :tours
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :review
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  # GET /reviews/1/posts
  def index
    #find the review for the id provided
    @review = Review.find(params[:review_id])
    @posts = @review.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @review = Review.find(params[:review_id])
    @post = @review.posts.find(params[:id])
  end

  # GET /posts/new
  # GET /reviews/1/posts/new
  def new
    @review = Review.find(params[:review_id])
    @post = @review.posts.build
  end

  # GET /posts/1/edit
  def edit
    @review = Review.find(params[:review_id])
    @post = @review.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @review = Review.find(params[:review_id])
    @post = @review.posts.build(post_params)

      if @post.save
        redirect_to review_post_url(@review, @post)
      else
        render :action => "new"
      end
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @review = Review.find(params[:review_id])
    @post = Post.find(params[:id])
      if @post.update_attributes(post_params)
        redirect_to review_post_url(@review, @post)
      else
        render :action =>"edit"
      end
    
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @review = Review.find(params[:review_id])
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to review_posts_path(@review) }
      format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_message)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@review, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_message %><br>
    <%= f.text_field :post_message %>
  </div>
  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', review_post_path(@review, @post) %> |
<%= link_to 'Back', review_posts_path(@review) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts in <%= @review.review_title %></h1>

<table>
  <thead>
    <tr>
      <th>Post message</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post_message %></td>
        <td><%= link_to 'Show', review_post_path(@review, post) %></td>
        <td><%= link_to 'Edit', edit_review_post_path(@review, post) %></td>
        <td><%= link_to 'Destroy', review_post_path(@review, post),
            :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_review_post_path(@review) %>
<%= link_to 'Back to Reviews', @review %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', review_posts_path(@review) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Post in <% @review.review_title %></h1>
<p>
  <%= @post.post_message %>
</p>

<%= link_to 'Edit', edit_review_post_path(@review, @post) %> |
<%= link_to 'Back', review_posts_path %>